slug = "gente-di-bruggi"
cover_image = "/static/img/gente_di_bruggi/Classe-1899-1900-1920-ca.jpg"

[it]
title = "Gente di Bruggi"
description = "Volti e ricordi degli abitanti di Bruggi nel corso degli anni."

[en]
title = "People of Bruggi"
description = "Faces and memories of Bruggi's inhabitants over the years."

[[images]]
url = "/static/img/gente_di_bruggi/Andrea-Giuseppe-Martino-Elio-1972.jpg"
alt = "Andrea Giuseppe Martino Elio 1972"

[[images]]
url = "/static/img/gente_di_bruggi/Antonietta-e-Giuseppina-(Lucia).jpg"
alt = "Antonietta e Giuseppina (Lucia)"

[[images]]
url = "/static/img/gente_di_bruggi/Classe-1899-1900-1920-ca.jpg"
alt = "Classe 1899 1900 1920 ca"

[[images]]
url = "/static/img/gente_di_bruggi/Gigio-1972.jpg"
alt = "Gigio 1972"

[[images]]
url = "/static/img/gente_di_bruggi/Ottavia-Tamburelli.jpg"
alt = "Ottavia Tamburelli"

[[images]]
url = "/static/img/gente_di_bruggi/PL_Ginota-e-amica.jpg"
alt = "Ginota e amica"

[[images]]
url = "/static/img/gente_di_bruggi/PL_Gruppo-di-famiglia-(1928).jpg"
alt = "Gruppo di famiglia (1928)"

[[images]]
url = "/static/img/gente_di_bruggi/PL_Gruppo-di-famiglia-(Primi-Novecento).jpg"
alt = "Gruppo di famiglia (Primi Novecento)"

[[images]]
url = "/static/img/gente_di_bruggi/PL_Pelle-Andrea-(du-Gian).jpg"
alt = "Pelle Andrea (du Gian)"

[[images]]
url = "/static/img/gente_di_bruggi/PL_Pelle Antonietta (1946).jpg"
alt = "Pelle Antonietta (1946)"

[[images]]
url = "/static/img/gente_di_bruggi/PL_Pelle-Antonietta-e-cognata.jpg"
alt = "Pelle Antonietta e cognata"

[[images]]
url = "/static/img/gente_di_bruggi/PL_Pelle-Giovanni-(Pumtto).jpg"
alt = "Pelle Giovanni (Pumtto)"

[[images]]
url = "/static/img/gente_di_bruggi/PL_Pelle-Vitale-e-Antonino.jpg"
alt = "Pelle Vitale e Antonino"

[[images]]
url = "/static/img/gente_di_bruggi/Scapolla-Luigi(Bufiggia).jpg"
alt = "Scapolla Luigi(Bufiggia)"

[[images]]
url = "/static/img/gente_di_bruggi/Scapolla-Pietro-Giuseppe-Luigi-Terenzio.jpg"
alt = "Scapolla Pietro Giuseppe Luigi Terenzio"

[[images]]
url = "/static/img/gente_di_bruggi/Scapolla-Pietro.jpg"
alt = "Scapolla Pietro"

[[images]]
url = "/static/img/gente_di_bruggi/senzatitolo.jpg"
alt = "senzatitolo"

[[images]]
url = "/static/img/gente_di_bruggi/SG-bersagliere.jpg"
alt = "bersagliere"

[[images]]
url = "/static/img/gente_di_bruggi/SG-Gigio.jpg"
alt = "Gigio"

[[images]]
url = "/static/img/gente_di_bruggi/SG-Gruppo1.jpg"
alt = "Gruppo1"

[[images]]
url = "/static/img/gente_di_bruggi/SG-gruppo.jpg"
alt = "gruppo"

[[images]]
url = "/static/img/gente_di_bruggi/SG-Nonni-di-Gino.jpg"
alt = "Nonni di Gino"

[[images]]
url = "/static/img/gente_di_bruggi/SG-nonno-di-Gino.jpg"
alt = "nonno di Gino"

[[images]]
url = "/static/img/gente_di_bruggi/SG-Scapolla-Pietro-(Dei).jpg"
alt = "Scapolla Pietro (Dei)"

[[images]]
url = "/static/img/gente_di_bruggi/SG-soldati.jpg"
alt = "soldati"

[[images]]
url = "/static/img/gente_di_bruggi/SG-soldato.jpg"
alt = "soldato"

[[images]]
url = "/static/img/gente_di_bruggi/SG-Trebbiatura.jpg"
alt = "Trebbiatura"

[[images]]
url = "/static/img/gente_di_bruggi/SL-gruppo-di-lavoro.jpg"
alt = "gruppo di lavoro"

[[images]]
url = "/static/img/gente_di_bruggi/SL-mulattieri1.jpg"
alt = "mulattieri1"

[[images]]
url = "/static/img/gente_di_bruggi/SL-mulattieri.jpg"
alt = "mulattieri"

[[images]]
url = "/static/img/gente_di_bruggi/Tamburelli-Antonio-1876-fatta-in-prussia-a-Metz.jpg"
alt = "Tamburelli Antonio 1876 fatta in prussia a Metz"

[[images]]
url = "/static/img/gente_di_bruggi/Tamburelli-Bernardo-ca-1930.jpg"
alt = "Tamburelli Bernardo ca 1930"

[[images]]
url = "/static/img/gente_di_bruggi/Tamburelli-Cesare-ca-1935.jpg"
alt = "Tamburelli Cesare ca 1935"

[[images]]
url = "/static/img/gente_di_bruggi/Tamburelli-Cesarina-ca-1925.jpg"
alt = "Tamburelli Cesarina ca 1925"

[[images]]
url = "/static/img/gente_di_bruggi/Tamburelli-Giuseppina-e-figlia-1937.jpg"
alt = "Tamburelli Giuseppina e figlia 1937"

[[images]]
url = "/static/img/gente_di_bruggi/TL-figlia.jpg"
alt = "figlia"

[[images]]
url = "/static/img/gente_di_bruggi/TL-foto-del-22-6-33.jpg"
alt = "foto del 22 6 33"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Geppo-(zio)1.jpg"
alt = "Geppo (zio)1"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Gita-del-1954.jpg"
alt = "Gita del 1954"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Gita.jpg"
alt = "Gita"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Guarco-(nonna-di-Lucia).jpg"
alt = "Guarco (nonna di Lucia)"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Moluggi-(Pietro).jpg"
alt = "Moluggi (Pietro)"

[[images]]
url = "/static/img/gente_di_bruggi/TL-ragazze-di-bruggi.jpg"
alt = "ragazze di bruggi"

[[images]]
url = "/static/img/gente_di_bruggi/TL-soldato.jpg"
alt = "soldato"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Tamburelli-Carlo.jpg"
alt = "Tamburelli Carlo"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Tamburelli-Francesca.jpg"
alt = "Tamburelli Francesca"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Tamburelli-Giovanni.jpg"
alt = "Tamburelli Giovanni"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Tamburelli-Lucia.jpg"
alt = "Tamburelli Lucia"

[[images]]
url = "/static/img/gente_di_bruggi/TL-Tamburelli-Pietro.jpg"
alt = "Tamburelli Pietro"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Barde.jpg"
alt = "Barde"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Don-Goglino.jpg"
alt = "Don Goglino"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Ferassa-Antonio(Buciou)-Tamburelli-Minchina.jpg"
alt = "Ferassa Antonio(Buciou) Tamburelli Minchina"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Gruppo1.jpg"
alt = "Gruppo1"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Nabucco-e-Virginio.jpg"
alt = "Nabucco e Virginio"

[[images]]
url = "/static/img/gente_di_bruggi/Vanoli-Agnese-Scapolla-Domenica.jpg"
alt = "Vanoli Agnese Scapolla Domenica"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Tamburelli-Carlo-(Bertei).jpg"
alt = "Tamburelli Carlo (Bertei)"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Tamburelli-Carlo-e- Agostina.jpg"
alt = "Tamburelli Carlo e Agostina"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Tamburelli-Carlo-e-Ferazza-Agostina.jpg"
alt = "Tamburelli Carlo e Ferazza Agostina"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Tamburelli-Giacomo.jpg"
alt = "Tamburelli Giacomo"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Tamburelli-Seconda.jpg"
alt = "Tamburelli Seconda"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Tamburelli-Tina.jpg"
alt = "Tamburelli Tina"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Tawina-e-la-madre-Maddalena.jpg"
alt = "Tawina e la madre Maddalena"

[[images]]
url = "/static/img/gente_di_bruggi/VA-Virginio-Rosa-Tawina-Maddalena.jpg"
alt = "Virginio Rosa Tawina Maddalena"
